version: '3'

services:
  baseservice:
    image: 'link_shortener-spring-boot-postgres:latest'
    build: link-shortener-base/
    container_name: link_shortener
    depends_on:
      - authenticationservice
    ports:
      - 8888:8888
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    restart: always

  authenticationservice:
    image: 'authenticationservice:latest'
    build: link-shortener-authenticationservice/
    depends_on:
      - postgres
    ports:
      - 9999:9999
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    restart: always

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres_for_link_shortener
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=links_db
    ports:
      - 5432:5432
    restart: always
