server:
  port: 9999
spring:
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    format-sql: true
    open-session-in-view: false
jwtExpirationMinutes: 1
secretKey: -KaPdSgVkYp3s5v8y/B?E(H+-KaPdSgVkYp3s5v8y/B?E(H+MbQeThWm