spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/links_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      fromat-sql: true
      ddl-auto: none
    open-session-in-view: false
expirationTimeMinutes: 3



